### ISSUE TITLE
installing with 2.7 causes a print failure

### ISSUE THREAD

**Issue by sean-abbott** [jjmontesl/python-clementine-remote#1]
I installed with 2.7 (which did not complain or refuse) using [pipsi](https://github.com/mitsuhiko/pipsi), which on my system defaults to python 2.7.

When attempting to run `--version`, I got an error because in 2.x, print is a keyword not a function:

```bash
$ clementine-remote --help
Traceback (most recent call last):
  File "/home/sean/.local/bin/clementine-remote", line 7, in <module>
    from clementineremote.cli import main
  File "/home/sean/.local/venvs/python-clementine-remote/local/lib/python2.7/site-packages/clementineremote/cli.py", line 74
    clementine.on_message = print
```
The fix for just that one command was simple: drop `from __future__ import print_function` at the top of the cli.py file.  (No idea if that would have further ramifications down the line.)

I was able to fix by installing with the python3 virtualenv instead (`pipsi install --python python3 python-clementine-remote`).

Ideally, if you require python3, a python2 install would fail.

**Comment by jjmontesl** [comment]
Thanks for the report.

This has been fixed in version 1.0.2 (#ec3ed6b), already available in PyPI.
